title: POP3.NET
description: Small and simple library for retrieving messages from Post Office Protocol version 3 (POP3) servers with full support for .NET 4.6, .NET Core 1.0, Windows Runtime and asynchronous programming model.
google_analytics: UA-33682454-1
show_downloads: true
theme: jekyll-theme-cayman

gems:
  - jekyll-mentions
